import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import './index.css'

// Register the Service Worker generated by vite-plugin-pwa.
// The SW file is auto-generated at build time; this import is a no-op in dev.
import { registerSW } from 'virtual:pwa-register'

registerSW({
  // Called when a new SW is waiting to activate.
  // For a kids app, auto-reload is fine — no complex state that would be lost.
  onNeedRefresh() {
    // Silently update: skip the "new version available" prompt.
    // Remove this and add UI if you want to give the user control.
  },
  onOfflineReady() {
    console.log('Pick Word is ready to work offline.')
  },
})

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
